Replace Gulp by Webpack
eveoh/room-display pull request #54
Opened 2020-09-23 11:50 UTC by troley

Ref. #???

## Proposed changes

WIP. 
1st changes involve configuring the development and production builds and everything involved around it (based on what the `gulpfile.js` does).

## Testing

WIP.
Run npm `build` / `clean` tasks successfully.

## Documentation

Does this change require updating the product documentation or help page? If yes, has this been taken care of? Or has a separate work item been created (reference here)?

## Upgrade notes for breaking changes

- [ ] `UPGRADE_NOTES.md` has been updated (when applicable).

2020-09-30 10:10 UTC, troley commented
Hij is nu van jou @MikeN123 .

2020-09-30 16:56 UTC, MikeN123 reviewed
Ik heb wel wat dingen op de Gradle file, maar dat is niet het belangrijkste denk ik.

Wat ik mij vooral afvraag is:

- Willen we nog wel Gradle gebruiken hier. In principe doet dit project niets met Java, en als we bij andere projecten naar een node/npm(of yarn)-only project gaan waarin we nog wel enigszins de node versie vastzetten, is de vraag misschien of we dat hier ook niet zouden moeten doen om het simpel te houden?
- Wat de Javascript betreft vraag ik me af of het nu redelijk in elkaar steekt. Maar het probleem daarbij is dat ik ook niet zoveel van Javascript weet. In principe zette deze app alles al in een `app` object. Dat object wordt nog steeds gehandhaafd, maar wordt nu overal gewoon maar uitgebreid, vanuit allerlei files. Ik weet niet of dat wel de manier is, of dat er een nettere manier is waarop het in elkaar gestoken zou moeten worden. Hangt natuurlijk ook af van hoeveel werk het is om te wijzigen. @evpaassen heb jij hier meer zicht op, of moet ik zelf nog even verder rondkijken?

2020-09-30 16:56 UTC, MikeN123 commented on build.gradle
> +buildscript {
Deze kan tegenwoordig naar `settings.gradle` in een mooier formaat. Zie `mytimetable-ec/settings.gradle`.

2020-09-30 16:56 UTC, MikeN123 commented on build.gradle
> +    id 'org.siouan.frontend-jdk8' version '4.0.0'
Is er een reden dat we niet gewoon de `jdk11` versie kunnen gebruiken?

2020-09-30 16:56 UTC, MikeN123 commented on build.gradle
> +    nodeInstallDirectory = file("${project.projectDir}/.nodejs")
Is er een reden dat we hier deze dir gebruiken, terwijl we bij MTT `${project.projectDir}/.gradle/nodejs` gebruiken, en de default van de plugin gewoon `${project.projectDir}/node` is?

2020-09-30 16:56 UTC, MikeN123 commented on build.gradle
> +uploadArchives.dependsOn tasks.webpackZip
Volgens mij zou die `artifacts` hierboven eigenlijk gewoon naar de output van die `webpackZip` moeten wijzen, dan hoef je die expliciete dependency niet toe te voegen. Exacte formaat weet ik zo 123 ook niet, maar volgens mij moet je hem gewoon netjes naar de taak kunnen laten wijzen.

2020-09-30 16:56 UTC, MikeN123 commented on build.gradle
> +tasks.register('webpackZip', RunNpmYarn) {
Deze taken definiëren hun input en output niet, dat zou eigenlijk wel mogen als het even kan.

2020-10-01 06:39 UTC, evpaassen requested changes
Als ik er even snel doorheen kijk, denk ik dat het wel een goed begin is, maar dat er nog wel wat kan verbeteren.

Zoals @MikeN123  aangaf, zou het netter zijn om ES6 modules te maken van de javascript-files, in plaats van overal het `App` object uit te breiden. Dat was waarschijnlijk ook ongeveer evenveel werk geweest.

Ik ben in dit project ook niet echt gehecht aan Gradle (want daardoor knoop je dit hele project ook weer aan Java) en wat mij betreft hoeft er ook geen onderscheid te zijn tussen een zip en een zipVersioned task. Er mag gewoon een `build` task zijn die altijd een versioned zip oplevert.

2020-10-01 06:39 UTC, evpaassen commented on src/main/resources/index.html
>      <script src="js/app.js"></script>
In plaats van het handmatig moeten includen van scripts e.d. kun je beter Webpack's html-loader gebruiken. Hier zit Thymeleaf niet in de weg, zoals in MyTimetable, want die is er niet.

2020-10-01 06:39 UTC, evpaassen commented on package.json
> +    "zipVersioned": "node ziptask.js --versioned"
Ik zie hier een hoop tasks die hetzelfde doen. En een hoop tasks die niet alles doen wat ik zou willen. Wat is het idee erachter?

Als ik een zip wil, wil ik alleen `npm/yarn run build` hoeven roepen. En `build:dev` voor een dev server.

2020-10-01 06:39 UTC, evpaassen commented on src/main/js/entry.js
> +import "./modules/updater";
Waarom staan alles modules in het entry point? Als je modules import vanuit waar ze nodig zijn, dan zou Webpack de rest automatisch voor je moeten regelen, toch?

2020-10-01 07:13 UTC, troley commented
Hm, over de opmerkingen over Gradle, misschien kan die er inderdaad uitgeknikkert worden, want die paar tasks die erin gedefinieerd worden die delegeren toch alleen maar naar de NPM tasks. Ik weet niet in hoeverre een soort `uploadArchives` task in NPM te realiseren is, maar ik neem aan dat dat niet echt iets heel bijzonders moet zijn en wel te realiseren moet zijn met NPM.

Over dat `app` object, ja, dat object wordt nu overal zo'n beetje rondgeslingerd en uitgebreid.. ik moest ook op wat plekken de code aanpassen zodat de `app` het weer deed. Een goede tip is denk ik de html-loader die Erik noemt, want op een html pagina ging het met het object mis. Dus ik ga nog even kijken naar meer ES6-style organisatie van de JavaScript files.

Hoe zit het trouwens met GitHub Actions in dit project (en ook andere projecten, echo-front bijv. viel mij ook op)? Willen we dat hier niet hebben @MikeN123 @evpaassen ? Misschien is dat iets voor na dit issue?

2020-10-01 07:15 UTC, troley commented on build.gradle
> +    id 'org.siouan.frontend-jdk8' version '4.0.0'
Ja, met JDK11 gaat het niet helemaal goed in dit project.
`java.lang.UnsupportedClassVersionError: org/siouan/frontendgradleplugin/FrontendGradlePlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0`

2020-10-01 07:16 UTC, troley commented on build.gradle
> +    nodeInstallDirectory = file("${project.projectDir}/.nodejs")
Hm nee dit pad is overgenomen uit de oude Gulp configuratie, maar niet echt een andere reden dan dat. Voor consistentie zal ik dat wel aanpassen, zodat dat overeenkomt met MTT.

2020-10-01 07:17 UTC, MikeN123 commented
Laten we het een beetje in stapjes doen. Misschien is het ook goed eerst echo-front af te maken. Die is namelijk verreweg het eenvoudigst, en dan kunnen we vanuit het resultaat daarvan deze ook weer verder aanpassen?

2020-10-01 07:17 UTC, troley commented on build.gradle
> +    nodeInstallDirectory = file("${project.projectDir}/.nodejs")
Nja of niet als Gradle eruit gaat.. 😛

2020-10-01 07:20 UTC, troley commented
> Laten we het een beetje in stapjes doen. Misschien is het ook goed eerst echo-front af te maken. Die is namelijk verreweg het eenvoudigst, en dan kunnen we vanuit het resultaat daarvan deze ook weer verder aanpassen?

Prima wat mij betreft.

2020-10-01 07:22 UTC, MikeN123 commented on build.gradle
> +    id 'org.siouan.frontend-jdk8' version '4.0.0'
Tsjah, dan moet je zorgen dat je met een Java 11 JDK het zaakje draait. Blijkbaar heb jij nu een Java 8 JDK?

2020-10-01 07:44 UTC, evpaassen commented
> Wat uploads betreft kun je natuurlijk wel een NPM package uploaden naar een NPM repository. Maar ik heb m'n twijfels of dat nou helemaal het formaat is wat we hier zoeken (uiteindelijk downloaden en unzippen we namelijk het resultaat weer, en moet er nog een configuratie in worden gezet). Lijkt mij iets om ook nog even verder te bekijken wanneer het in de basis klopt. Misschien kan er wel gewoon een NPM upload gebruikt worden, want uiteindelijk wordt het hele pakket dan volgens mij wel in een tarball gestopt en geupload.

Volgens mij kun je hiervoor ook gewoon een RAW repository gebruiken en uploaden via de REST API: https://support.sonatype.com/hc/en-us/articles/115006744008-How-can-I-programmatically-upload-files-into-Nexus-3-

2020-10-01 08:22 UTC, MikeN123 commented
Ja dat hij ergens geupload kan worden geloof ik op zich wel. Ik denk dat het punt meer client-side zit. Als je gewoon een `npm publish` ofzo kan doen is dat waarschijnlijk minder custom code dan zelf dingen moeten zippen en moeten uploaden. Maar ik weet daarbij niet goed wat de standaard publicatieacties van npm doen, en in hoeverre dat afwijkt van de eigen zips.

2020-10-07 17:40 UTC, troley commented
Ik heb hier een aantal commits op een hoop gegooid (specifieker op de 1e en de 2e commit, omdat dat 1 geheel vormde; rebasen zonder dat te doen wou niet erg goed gaan). Daarnaast is de laatste fixup commit iets wat ik zelf gespot had, wat ik vergeten was te doen. De 3 na laatste commits zijn changes op Erik z'n opmerkingen. Ik heb nog niet aan het 'uitschakelen van Gradle / andere package manager introduceren' gezeten, dat moet nog komen.

2020-10-07 17:44 UTC, troley commented on src/main/js/main.js
>                          setTimeout(function() { location.reload(false); }, 60);
Wat mij trouwens opviel, deze timeout en de timout 7 lines hieronder hebben een timout van 60 ms. Als er iets foutgaat bij bijv. het fetchen van config, dan blijft de browser iets te snel refreshen. Was dat ooit de bedoeling zo'n lage ms in te stellen? Of moest dat een hoger getal worden?

2020-10-07 17:51 UTC, MikeN123 commented on src/main/js/main.js
>                          setTimeout(function() { location.reload(false); }, 60);
:') lijkt mij dat daar 60 seconden werd bedoeld, goed gespot.

2020-10-08 09:27 UTC, MikeN123 commented
Volgens mij gaat het zo al een betere kant op. Heb er nog niet in detail naar gekeken. Was het de bedoeling dat dat wel gebeurde, of kijken we daarnaar nadat `echo-front` afgerond is?

Een ding wat ik in ieder geval zag is dat manifest. Volgens mij moeten we daar iets mee, want die referenties daarin kunnen niet meer kloppen na een webpack build, want volgens mij hou je alleen de namen van je entrypoints en vendor over (al dan niet met cache breaker). Mogelijk moet het manifest dus ook door webpack heen gaan, of hoe dat dan ook werkt. Bij dit project zijn cachebreakers door het manifest mogelijk niet nodig, not sure, maar die zitten er op dit moment nog niet in.

2020-10-08 09:58 UTC, troley commented
Hm ik denk dat het handig is om eerst die `echo-front` goed te krijgen en daarna dit in detail te bekijken. Ik ging hier maar even tussentijds aan werken toen echo-front op review stond te wachten.

Die referenties die kloppen nog wel. Dat zijn bestanden die in de output (`dist/`) dir terecht komen. Dat zijn de html, js en css (entrypoints), images, config.json en manifest.appcache bestanden. Deze staan er zonder een cache breaker in, omdat de `manifest.appcache` bestand inderdaad voor de caching van die bestanden zorgt. In iedergeval zag ik bij de tests dat precies de bestanden die erin genoemd staan gecached worden door de browser.

2020-11-03 09:49 UTC, troley commented
@MikeN123 Hierbij wat context over het gebruik van CopyWebpackPlugin in dit project:

Het idee hier met de CopyWebpackPlugin hier was, dat sommige assets die door JS / HTML gebruikt worden gekopierd worden naar de output dir. Specifiek betreft dit op dit moment de `images/`, de `manifest.appcache` en `config.json` bestanden.

Bij de `manifest.appcache` en `config.json` kan ik mij voorstellen dat we soortgelijk iets kunnen doen als wat bij echo-front is besproken, namelijk de splitsing maken `dev-server/` en `dist/` en op de `dev-server/` de contentBase laten luisteren en bij `dist/` de content meenemen bij het tar packagen. Daarnaast wordt bij `manifest.appcache` ook de content met een CopyWebpackPlugin functie aangepast, zodat de caching correct blijft werken. Bij het tar packagen zou de content vooraf getransformeerd kunnen worden, bij het instellen van de contentBase is er wellicht een devServer property die vooraf/achteraf de transformatie zou kunnen doen. Of misschien is het bij development zelfs niet zo belangrijk.

Dan hebben we nog de images in `images/`. Deze worden 1:1 naar `images/` gekopieerd in de output dir. De paden in de HTML-bestanden staan statisch op dat pad ingesteld. Met die image paden doet Webpack dus verder ook niets dynamisch.

Er is een `html-loader` Webpack loader die de paden naar images (en dergelijke assets) dynamisch kon setten, maar ik meen mij te herinneren, dat toen ik daarmee aan de slag ging het voor geen meter wou werken. Ik vermoed dat dat te maken had met het feit dat de images middels `<link ... href="..." />` ingeladen worden en `html-loader` die tag/attribute combinatie voor images [niet support](https://webpack.js.org/loaders/html-loader/#attributes) . Maar ik weet even niet meer precies of dat echt het probleem was. Zou ik nog een keer naar moeten kijken.

2020-11-03 12:07 UTC, MikeN123 commented
Ok, thanks. Maak er eerst maar een PR van zoals jij vindt dat het OK is, en dan kijken we er dan wel even verder naar.

2020-11-06 09:01 UTC, marcokrikke commented
Het viel me hier nog op dat `updater.js` nergens (meer) wordt gebruikt. Klopt dat?

2020-11-06 09:43 UTC, troley commented
TL;DR:
Hij wordt wel gebruikt, alleen valt dat niet meteen op, omdat hij door een event wordt getriggered.

Uitleg:
Het valt hier misschien op het 1e ogenblik niet op, maar de updater wordt bij een `app:start` event gestart. Die event wordt getriggered in `main.js`. In de `updater.js` (en andere modules op verschillende plekken) wordt een
```
eventBus.on(...)
```
geregistreerd die luistert naar die event. Het doet nog steeds wat het in de oude situatie deed, alleen is het globale `app` object dat overal soort van werd ge-extend, door er steeds meer properties aan toe te kennen, is eruit gesloopt. De `eventBus` wordt aangemaakt in `main.js` en wordt geimport door modules die het object willen gebruiken, dus ook door `updater.js`.

2020-11-06 14:59 UTC, troley commented
@MikeN123 Ik heb hier nog de review punten van Erik meegenomen die in echo-front genoemd waren. 

Daarnaast was ik vergeten te vermelden dat ik dat vervangen van CopyWebpackPlugin door de loaders voor nu voor de duidelijkheid in een aparte commit houd (is denk ik duidelijk aan de naam te zien welke dat is). Uiteindelijk squash ik het een en ander nog wel.

2020-11-09 19:37 UTC, MikeN123 reviewed
Ik heb er nog niet heel intensief naar gekeken.

Het voornaamste wat me opvalt is de scheiding tussen de verschillende modules. Ik vraag me op veel plekken af of we niet een duidelijkere scheiding zouden kunnen hanteren. Uiteindelijk wil je dat zoveel mogelijk onderdelen van de applicatie op zichzelf staan. Nu heb ik ook niet zoveel kaas gegeven van Javascript app development, dus heb niet meteen het antwoord in huis, maar misschien dat je er zelf al wat ideeën bij hebt?

2020-11-09 19:37 UTC, MikeN123 commented on src/js/api-client.js
> +eventBus.on("app:config", function() {
Ik heb hierbij toch wel sterk het idee dat die apiclient dit niet zelf zou moeten doen. Ik zie die apiclient als een 'losse module' die helemaal niets weet van de rest van de applicatie.

De configuratie zou hij dus ergens in het initialisatieproces moeten krijgen eigenlijk, en niet zelf ineens op moeten pikken. Want als je in een andere app dezelfde apiclient zou willen gebruiken kan dat nu niet.

2020-11-09 19:37 UTC, MikeN123 commented on src/js/main.js
> +function mergeConfig(baseConfig, overrideConfig) {
Die config merging zou er dus uit kunnen als we gewoon met 1 config gaan werken, scheelt weer code.

2020-11-09 19:37 UTC, MikeN123 commented on src/js/main.js
> +export const eventBus = $({});
Die eventBus zou van mij wel naar een eigen file mogen, dan is duidelijk wie precies die eventbus gebruiken, ipv dat iedereen in `main` loopt te roeren.

2020-11-09 19:37 UTC, MikeN123 commented on src/js/modules/settings.js
> +import { NS, appConfig, eventBus, fragments } from "../main";
Er wordt hier van alles uit `main` gehaald. Ook verschillende andere files doen dat. Zoals ik het zie zou main eigenlijk helemaal niets zelf moeten exporten, maar moeten allemaal andere modules dat doen en zou main het alleen aan elkaar moeten knopen.

Hoe zie jij dat, en kun je eens kijken of we dit beter op kunnen splitsen? Ik ben er niet in detail doorheen gegaan, dus heb geen kant en klare oplossing voor je, maar hopelijk snap je het punt?

Ik weet overigens niet wat een mooie manier is om die `NS` constante te exporteren. Gezien die volgens mij alleen maar voor localStorage wordt gebruikt is het de vraag of er niet een aparte module zou moeten zijn die dat soort zaken regelt en die namespace daarmee in zich heeft.

2020-11-09 19:37 UTC, MikeN123 commented on webpack.common.js
> +                // Groups output CSS files into a single file. Otherwise there will be multiple CSS files with
Ik weet dat we dit in MTT hebben gedaan door gewoon een apart entrypoint te maken. Dit kan ook, vraag me wel af wat nu de fatsoenlijke methode is... niet direct een idee bij.
In dat geval zou je dus bij je `HtmlWebpackPlugin` meer dan 1 chunk specificeren.

2020-11-09 19:37 UTC, MikeN123 commented on webpack.common.js
> +        new MiniCssExtractPlugin({ filename: "css/[name].css", }),
We zouden denk ik nog wel even een ei willen leggen over de exacte plek van die output. Gezien het nu nog samenhangt met `manifest.appcache` en het dus later misschien weer wijzigt is het nu wel ok denk ik, maar moeten we in de PR die dat ombouwt er misschien nog eens naar kijken? Anders moeten we 2x verzinnen waar alles zou moeten staan.

2020-11-10 08:53 UTC, troley commented on README.md
> +- Adjust the configuration in `config/config.json` to suit your situation.
Uh, ja dit ding begon bij mij toen ook al een beetje te rinkelen en dit bevestigt het dus.

2020-11-10 08:54 UTC, troley commented on package.json
> +    "upload": "mvn-up -g nl.eveoh.mytimetable -a ${npm_package_name} -v ${npm_package_version} -f ./build/distributions/${npm_package_name}-${npm_package_version}.tar.gz -P tar.gz"
Ja mee eens. Ik heb dit overgenomen uit de oude Gradle config, maar vond ook dat het onder een eigen group mocht vallen. In de oude situatie was het `nl.eveoh.mytimetable-${customer}`, maar dat `-${customer}` deel heb ik gedropt, doordat we 1 build willen hanteren.

2020-11-10 08:56 UTC, MikeN123 commented on package.json
> +    "upload": "mvn-up -g nl.eveoh.mytimetable -a ${npm_package_name} -v ${npm_package_version} -f ./build/distributions/${npm_package_name}-${npm_package_version}.tar.gz -P tar.gz"
In dat kader is er ook nog een override SASS file geloof ik. Haal die er ook maar uit (incl. de referentie die volgens mij in de README staat ofzo?)
Ik zie nu alleen een custom branch voor CSU, maar daarvan is het nog maar de vraag of ze uberhaupt klant blijven op het moment.

2020-11-10 08:57 UTC, troley commented on src/js/api-client.js
> +eventBus.on("app:config", function() {
Hm ja, dus dat in dit geval de dependency omgedraait wordt -> `api-client` weet niets af van `main`, `main` kent en gebruikt `api-client`. Is denk ik wel beter. Ik heb het andersom gedaan, `main` kent/gebruikt niks en de andere modules (ook `api-client`) kennen/gebruiken main z'n spullen.

2020-11-10 08:58 UTC, troley commented on webpack.common.js
> +                // Groups output CSS files into a single file. Otherwise there will be multiple CSS files with
Ja het is inderdaad of het 1 of het andere. In het geval dat het een aparte entry wordt moet inderdaad een extra chunk opgenomen worden in de `HtmlWebpackPlugin`.

2020-11-10 10:02 UTC, troley commented on src/js/modules/settings.js
> +import { NS, appConfig, eventBus, fragments } from "../main";
Ik snap het punt. ik heb het nu precies andersom gedaan, `main` die kent de andere modules niet en doet z'n ding en triggert events, en de rest importeert spullen uit `main`. Het klinkt logischer om alles in `main` te gebruiken en niet andersom.

Het voelt toch zo vaag aan doordat die `eventBus` events toch stiekem voor dependencies zorgen. Naar mijn gevoel zouden we die `eventBus` er op meerdere plekken niet willen hebben en gewoon harde dependencies hebben op de properties/functies van de desbetreffende modules, maar ik denk dat dat mogelijk problematisch zou worden.

In ieder geval ga ik kijken of die `eventBus` en de `NS` een apart, op zich zelf staand iets kunnen worden en de dependencies omdraaien, dus dat `main` de modules gebruikt en dat de modules zich niet bemoeien met `main` (op de `eventBus` events na).

2020-11-10 10:15 UTC, troley commented on webpack.common.js
> +        new MiniCssExtractPlugin({ filename: "css/[name].css", }),
Hm, wat je hierbij bedoelt is dus dat we een aparte dir kunnen verzinnen waar alle spullen die gecached worden in komen te zitten, zodat op die hele dir een ServiceWorker kan gaan luisteren, begrijp ik dat goed? 

Als dat zo is, dan is dat wel handig om daar bij de PR die dat ombouwt er nog eens naar te kijken, ja. Volgens mij werd het al ergens ooit genoemd dat er een aparte `assets` dir kon komen, waarin alles gecached kan worden. Zo iets zou hier misschien ook kunnen na de verbouwing.

2020-11-10 14:31 UTC, MikeN123 commented on webpack.common.js
> +        new MiniCssExtractPlugin({ filename: "css/[name].css", }),
Nee, ik bedoel niks met serviceworkers specifiek.

Wat ik bedoel is dat in `echo-front` we uiteindelijk alles in `bundles` ofzo hebben gezet, en niet meer die hele opsplitsing tussen `css`, `img` en `js` in de output hadden. Die zit hier nu nog wel in.

Maar zoals gezegd zou het kunnen zijn dat die indeling nog verder wijzigt als er serviceworkers gebruikt worden, dus misschien zou het hier nu dus nog even zo moeten blijven.

2020-11-10 15:21 UTC, MikeN123 commented on src/js/modules/settings.js
> +import { NS, appConfig, eventBus, fragments } from "../main";
Ja je wilt uiteindelijk eigenlijk altijd 'dependency inversion'. Dus alle modules (classes, of hoe je ze ook wilt noemen) doen hun eigen taak, en hebben niet met de rest te maken.

Dat betekent niet dat we nu ineens alles om zouden moeten gooien, dat niet. Maar we kunnen wel even kritisch kijken naar wat nu precies aan wat hangt, en in ieder geval zorgen dat dingen die eigenlijk gewoon losse dingen zijn (zoals de eventbus, of het opslaan van iets in local storage adhv de namespace) ook los staan van de rest. Ik denk niet dat die `NS` zelf als 1 dingetje losgezet zou moeten worden eigenlijk, maar dat je misschien gewoon een simpele module wil hebben die iets opslaat en iets ophaalt uit de local storage, en dan die `NS` toepast. Maar ik weet niet om hoeveel verschillende methodes dat potentieel gaat (je wil niet een enorme module moeten klussen die eigenlijk alle localstorage functionaliteit repliceert). Kijk dus even wat handig is.

2020-11-11 07:19 UTC, troley commented
> Het viel me hier nog op dat `updater.js` nergens (meer) wordt gebruikt. Klopt dat?

Je had hier gelijk @marcokrikke . Hij werd inderdaad niet opgepakt door webpack. Ik kwam er gisteren achter doordat ik in de module de `override` config stuff aan het verwijderen was.

Erger nog, de app werkt(e al) niet in development als die `updater.js` wel wordt opgepakt, omdat de `window.applicationCache` niet over een unsecured context (HTTP) gebruikt kan worden (zie https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache - het gele warning bericht bovenaan). In productie over HTTPS merk je daar dus denk ik weinig van. Uiteindelijk kan die `updater.js` er toch uit met de nieuwe ServiceWorker methode. Ik kijk nog of ik dit kan fixen voor development mode.

`clock.js` werd overigens ook niet opgepakt, merkte ik.

2020-11-11 07:25 UTC, MikeN123 commented
Ik zou geen moeite doen om die serviceworkers te fixen voor devmode hoor. Ik denk dat dat lastig tot niet gaat, en als het er toch uit gaat...

2020-11-11 07:33 UTC, troley commented
In dat geval denk ik dat die `updater.js` module er helemaal uit kan, voor 90% zocht het naar `override` config changes en die andere 10% gaat naar `window.applicationCache.update()` deze line, die ervoor zorgt dat er gecheckt wordt of er geen nieuwe manifest file is, waarna er mogelijk nog een page reload gedaan wordt.

2020-11-11 08:05 UTC, MikeN123 commented
Die laatste is natuurlijk nog wel relevant in productie op dit moment, zolang die applicationCache er nog niet helemaal uit is. Maar het is inderdaad niet per se het belangrijkste.

2020-11-11 16:23 UTC, troley commented
In de 1e en 1 na laatste fixup zitten de `eventBus` en de `NS` in een aparte `app-storage.js` geextraheerd, maar met name zitten er in deze fixups de verwijdering van `override` config stuff en de veranderingen in de dependencies van de verschillende modules en `main`.

De configuratie en `fragments` die `main` eerst exporteerde naar de andere modules, worden nu tijdens de initialisatie proces in `main` aan de desbetreffende modules die het gebruiken meegegeven. Tevens wordt `main` hiermee ook de entry point geworden voor alle views, behalve de `error` view. `error` gebruikt een eigen entry point.

Modules onderling gebruiken elkaar ook als dependencies als ze elkaar nodig hebben. Zo zie je bijv. bij `schedule.js` dat die `clock.js` importeert, omdat hij hier via de eventBus van afhankelijk is. `clock.js` z'n properties en functies zijn hier niet van belang, maar hij moet wel geimporteerd worden, anders bestaat die niet voor Webpack.

2020-12-10 11:08 UTC, troley commented
@MikeN123 ik heb hier dus nog een keer naar gekeken en heb alleen een irrelevante line uit `.idea/misc.xml` weggehaald. Ik vind dat het nu te reviewen is.

1 schoonheids dingetje dat mij nog opviel is dat we misschien de module init functies in main (e.g. `initApiClient`) nog in de modules zelf in een export default blok zouden kunnen zetten en dat deze dan in plaats van bijv. `initApiClient` gewoon `initialize` genoemd zouden kunnen worden en dat de module dan bij zijn naam geimporteerd zou kunnen worden. Die zou vervolgens de `initialize` functie kunnen roepen. Deze aanpassing zou ervoor zorgen dat de modulenamen niet in de functienaam zouden voor komen.
Ik post hier nog een temp commit van van 1 van de modules, dat licht dan denk ik beter toe wat ik hiermee bedoel.

2021-01-05 15:29 UTC, marcokrikke approved these changes
Paar kleine issues eruit gehaald en één grote (incorrecte/missende entries in appcache manifest). Verder alle functionaliteit getest.

2021-01-05 15:30 UTC, merged